config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get 'pages/feed'

  get 'pages/about'
  
  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def feed
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewNews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    
    <div class="center"><%= render "shared/nav_bar" %></div>
    
  <body class="Background">
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1  class="center">About Us</h1>
  <h2 class="Sub">Authors of Site</h2>
  <p class="Sub">Ryan McMurray Sebastian Garcia Spencer Hanson</p>

app/views/pages/feed.html.erb
<h1  class="center">New News Feed</h1>
  <h2 class="Sub">interesting subtitle</h2>
  
  <body>
    <img class="image" src="https://www.starwarsnewsnet.com/wp-content/uploads/2017/07/Inferno-Squad_Spoiler-Review.png" alt="" width="500" height="393" srcset="https://www.starwarsnewsnet.com/wp-content/uploads/2017/07/Inferno-Squad_Spoiler-Review.png 868w, https://www.starwarsnewsnet.com/wp-content/uploads/2017/07/Inferno-Squad_Spoiler-Review-300x236.png 300w, https://www.starwarsnewsnet.com/wp-content/uploads/2017/07/Inferno-Squad_Spoiler-Review-768x603.png 768w" sizes="(max-width: 500px) 100vw, 500px">
    <h3 class="center">Inferno Squad Resurfaces After 30 Years Missing</h3>
      
      <img class="image" src="https://vignette3.wikia.nocookie.net/starwars/images/0/09/FOSpecForcesTIE1-Fathead.png/revision/latest?cb=20161109002850">
      <h3 class="center">The First Order Deploys New SpecOps Tie fighter To "Combat The Growing Threat Of The New Republic"</h3>
  </body>

app/views/pages/home.html.erb
<h1 class="center">First Order Propaganda</h1>
  <h2 class="Sub">Obey Or Die</h2>
    <img class="home_image" src="https://vignette4.wikia.nocookie.net/starwars-ar/images/d/d1/First_Order.png/revision/latest?cb=20151220180054">
<p class="center">Remember Taxes Support Your Military, Pay Your Share or be Penalized</p>

app/views/shared/_nav_bar.html.erb
<div class="center"><%= link_to 'Home', pages_home_path %>
<%= link_to 'Feed', pages_feed_path %>
<%= link_to 'About', pages_about_path %></div>